import { Metadata } from 'next';

const cityNames: Record<string, string> = {
  // Tamil Nadu - All 38 districts
  "chennai": "Chennai",
  "coimbatore": "Coimbatore",
  "madurai": "Madurai",
  "trichy": "Trichy",
  "tiruppur": "Tiruppur",
  "salem": "Salem",
  "erode": "Erode",
  "vellore": "Vellore",
  "thoothukudi": "Thoothukudi",
  "thanjavur": "Thanjavur",
  "dindigul": "Dindigul",
  "nagercoil": "Nagercoil",
  "kancheepuram": "Kancheepuram",
  "karur": "Karur",
  "tirunelveli": "Tirunelveli",
  "ariyalur": "Ariyalur",
  "chengalpattu": "Chengalpattu",
  "cuddalore": "Cuddalore",
  "dharmapuri": "Dharmapuri",
  "kallakurichi": "Kallakurichi",
  "krishnagiri": "Krishnagiri",
  "mayiladuthurai": "Mayiladuthurai",
  "nagapattinam": "Nagapattinam",
  "namakkal": "Namakkal",
  "perambalur": "Perambalur",
  "pudukkottai": "Pudukkottai",
  "ramanathapuram": "Ramanathapuram",
  "ranipet": "Ranipet",
  "sivaganga": "Sivaganga",
  "tenkasi": "Tenkasi",
  "ooty": "Ooty",
  "theni": "Theni",
  "thiruvallur": "Thiruvallur",
  "thiruvarur": "Thiruvarur",
  "tirupathur": "Tirupathur",
  "tiruvannamalai": "Tiruvannamalai",
  "viluppuram": "Viluppuram",
  "virudhunagar": "Virudhunagar",
  // Karnataka - All 31 districts
  "bangalore": "Bangalore",
  "mysore": "Mysore",
  "mangalore": "Mangalore",
  "hubli": "Hubli",
  "belgaum": "Belgaum",
  "gulbarga": "Gulbarga",
  "tumkur": "Tumkur",
  "davanagere": "Davanagere",
  "bellary": "Bellary",
  "shimoga": "Shimoga",
  "bagalkote": "Bagalkote",
  "bengaluru-rural": "Bengaluru Rural",
  "bidar": "Bidar",
  "chamarajanagar": "Chamarajanagar",
  "chikkaballapura": "Chikkaballapura",
  "chikkamagaluru": "Chikkamagaluru",
  "chitradurga": "Chitradurga",
  "dharwad": "Dharwad",
  "gadag": "Gadag",
  "hassan": "Hassan",
  "haveri": "Haveri",
  "kodagu": "Kodagu",
  "kolar": "Kolar",
  "koppal": "Koppal",
  "mandya": "Mandya",
  "raichur": "Raichur",
  "ramanagara": "Ramanagara",
  "udupi": "Udupi",
  "karwar": "Karwar",
  "bijapur": "Bijapur",
  "yadgir": "Yadgir",
  "vijayanagara": "Vijayanagara",
  // UAE & Gulf Countries - All 42 cities
  // UAE
  "dubai": "Dubai",
  "abu-dhabi": "Abu Dhabi",
  "sharjah": "Sharjah",
  "ajman": "Ajman",
  "ras-al-khaimah": "Ras Al Khaimah",
  "fujairah": "Fujairah",
  // Qatar
  "doha": "Doha",
  "al-wakrah": "Al Wakrah",
  "al-khor": "Al Khor",
  "lusail": "Lusail",
  "mesaieed": "Mesaieed",
  "dukhan": "Dukhan",
  "umm-salal": "Umm Salal",
  // Oman
  "muscat": "Muscat",
  "ruwi": "Ruwi",
  "seeb": "Seeb",
  "sohar": "Sohar",
  "salalah": "Salalah",
  "nizwa": "Nizwa",
  "ibri": "Ibri",
  "sur": "Sur",
  // Saudi Arabia
  "riyadh": "Riyadh",
  "jeddah": "Jeddah",
  "dammam": "Dammam",
  "al-khobar": "Al Khobar",
  "jubail": "Jubail",
  "yanbu": "Yanbu",
  "makkah": "Makkah",
  "madinah": "Madinah",
  "al-ahsa": "Al Ahsa",
  // Kuwait
  "kuwait-city": "Kuwait City",
  "farwaniya": "Farwaniya",
  "salmiya": "Salmiya",
  "hawally": "Hawally",
  "fahaheel": "Fahaheel",
  "mangaf": "Mangaf",
  "ahmadi": "Ahmadi",
  // Bahrain
  "manama": "Manama",
  "muharraq": "Muharraq",
  "riffa": "Riffa",
  "sitra": "Sitra",
  "isa-town": "Isa Town",
};

export async function generateMetadata({ params }: { params: { city: string } }): Promise<Metadata> {
  const city = params.city.toLowerCase();
  const cityName = cityNames[city] || params.city;

  return {
    title: `Best NATA & JEE B.Arch Coaching in ${cityName} | Online Classes | Neram Classes`,
    description: `Top NATA and JEE B.Arch online coaching for students in ${cityName}. Save time with daily 30-60 min classes. Expert faculty, proven results. Join 1000+ successful students.`,
    keywords: [
      `NATA coaching ${cityName}`,
      `JEE B.Arch coaching ${cityName}`,
      `architecture coaching ${cityName}`,
      `online NATA classes ${cityName}`,
      `best NATA coaching ${cityName}`,
      `architecture entrance exam ${cityName}`,
      `NATA preparation ${cityName}`,
      `online architecture classes ${cityName}`,
    ],
    openGraph: {
      title: `NATA & JEE B.Arch Coaching in ${cityName} | Neram Classes`,
      description: `Expert online coaching for architecture entrance exams. Perfect for busy school students in ${cityName}.`,
      type: 'website',
    },
  };
}
