import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Handlee,
  Roboto,
  Bakbak_One,
  Poppins,
  Suez_One,
} from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { SessionProvider } from "@/contexts/SessionContext";
import ProfileGuard from "./components/shared/ProfileGuard";
import ChatBubbles from "../components/ChatBubbles";
import SnackbarNotice from "./components/shared/SnackbarNotice";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Additional fonts via next/font (preferred over <link> for performance)
const handlee = Handlee({
  variable: "--font-handlee",
  subsets: ["latin"],
  weight: "400",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
});

const bakbakOne = Bakbak_One({
  variable: "--font-bakbak-one",
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const suezOne = Suez_One({
  variable: "--font-suez-one",
  subsets: ["latin"],
  weight: "400",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://example.com";

export const metadata: Metadata = {
  title: "Neram Classes",
  description: "Generated by create next app",
  metadataBase: new URL(siteUrl),
  openGraph: {
    url: siteUrl,
    siteName: "Neram Classes",
    type: "website",
  },
  alternates: {
    canonical: "/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const recaptchaKey = process.env.NEXT_PUBLIC_RECAPTCHA_ENTERPRISE_SITE_KEY;

  return (
    <html lang="en">
      <head>
        <meta name="emotion-insertion-point" content="" />
        {recaptchaKey && (
          <script
            src={`https://www.google.com/recaptcha/enterprise.js?render=${recaptchaKey}`}
            async
            defer
          />
        )}
        {/* Inline script to hide reCAPTCHA badge immediately */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Function to hide reCAPTCHA badge
                function hideRecaptchaBadge() {
                  const badges = document.querySelectorAll('.grecaptcha-badge, [class*="grecaptcha-badge"]');
                  badges.forEach(function(badge) {
                    if (badge) {
                      badge.style.visibility = 'hidden';
                      badge.style.opacity = '0';
                      badge.style.display = 'none';
                      badge.style.width = '0';
                      badge.style.height = '0';
                      badge.style.position = 'absolute';
                      badge.style.overflow = 'hidden';
                      badge.style.zIndex = '-9999';
                    }
                  });
                }

                // Run immediately
                hideRecaptchaBadge();

                // Run after DOM is loaded
                if (document.readyState === 'loading') {
                  document.addEventListener('DOMContentLoaded', hideRecaptchaBadge);
                } else {
                  hideRecaptchaBadge();
                }

                // Run after window is fully loaded
                window.addEventListener('load', hideRecaptchaBadge);

                // Use MutationObserver to catch dynamically added badges
                var observer = new MutationObserver(function(mutations) {
                  hideRecaptchaBadge();
                });

                // Start observing when DOM is ready
                if (document.body) {
                  observer.observe(document.body, {
                    childList: true,
                    subtree: true
                  });
                } else {
                  document.addEventListener('DOMContentLoaded', function() {
                    observer.observe(document.body, {
                      childList: true,
                      subtree: true
                    });
                  });
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${handlee.variable} ${roboto.variable} ${bakbakOne.variable} ${poppins.variable} ${suezOne.variable}`}
      >
        <ThemeRegistry>
          <SessionProvider enableTracking={true} autoTrackNavigation={true}>
            <ProfileGuard>{children}</ProfileGuard>
            <ChatBubbles />
            <SnackbarNotice />
          </SessionProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
