import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Handlee,
  Roboto,
  Bakbak_One,
  Poppins,
  Suez_One,
} from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import ProfileGuard from "./components/shared/ProfileGuard";
import ChatBubbles from "../components/ChatBubbles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Additional fonts via next/font (preferred over <link> for performance)
const handlee = Handlee({
  variable: "--font-handlee",
  subsets: ["latin"],
  weight: "400",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
});

const bakbakOne = Bakbak_One({
  variable: "--font-bakbak-one",
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const suezOne = Suez_One({
  variable: "--font-suez-one",
  subsets: ["latin"],
  weight: "400",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://example.com";

export const metadata: Metadata = {
  title: "Neram Classes",
  description: "Generated by create next app",
  metadataBase: new URL(siteUrl),
  openGraph: {
    url: siteUrl,
    siteName: "Neram Classes",
    type: "website",
  },
  alternates: {
    canonical: "/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="emotion-insertion-point" content="" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${handlee.variable} ${roboto.variable} ${bakbakOne.variable} ${poppins.variable} ${suezOne.variable}`}
      >
        <ThemeRegistry>
          <ProfileGuard>{children}</ProfileGuard>
          <ChatBubbles />
        </ThemeRegistry>
      </body>
    </html>
  );
}
