import type { MetadataRoute } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://example.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow: [
          "/api/",
          "/account",
          "/account/*",
          "/auth",
          "/auth/*",
          "/profile",
          "/profile/*",
          "/settings",
          "/accountSettings",
          "/applications",
          "/applications/*",
          "/dashboard",
          "/dashboard/*",
          // Old duplicate city/location URLs
          "*-url",
          "/pudukkottai-url",
          "/tamilnadu-url",
          "/cochin-url",
          "/aat-url",
          "/vizag-url",
          "/salem-url",
          "/bangalore-url",
          "/hyderabad-url",
          "/delhi-url",
          "/erode-url",
          "/tirunelveli-url",
          "/malapuram-url",
          "/ooty-url",
          "/perambur-url",
          "/andhrapradesh-url",
          // Old paths
          "/test-page/*",
          "/wp-admin/*",
          "/register/*",
          "/members/*",
          "/NATA-coaching-centers-nearby/*",
          "/NATA_Coaching_center_near_me_address",
          "/Application-form-Nata-Coaching",
          "/Free-Nata-Class-books-online-registration",
          "/NATA_Application_Form_*",
          "/FAQs-nata-exam-questions",
          "/JEE_B.arch_Syllabus",
          "/NATA_Best_Architecture_Colleges",
          "/NATA_Free_Books",
          "/materials",
          // Disallow all .html files (duplicates)
          "/*.html",
          // Special characters
          "/&",
          "/$",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: ["/"],
        disallow: [
          "/api/",
          "/account",
          "/account/*",
          "/auth",
          "/auth/*",
          "/profile",
          "/profile/*",
          "/settings",
          "/accountSettings",
          "/applications",
          "/applications/*",
          "/dashboard",
          "/dashboard/*",
          // Old duplicate city/location URLs
          "*-url",
          "/pudukkottai-url",
          "/tamilnadu-url",
          "/cochin-url",
          "/aat-url",
          "/vizag-url",
          "/salem-url",
          "/bangalore-url",
          "/hyderabad-url",
          "/delhi-url",
          "/erode-url",
          "/tirunelveli-url",
          "/malapuram-url",
          "/ooty-url",
          "/perambur-url",
          "/andhrapradesh-url",
          // Old paths
          "/test-page/*",
          "/wp-admin/*",
          "/register/*",
          "/members/*",
          "/NATA-coaching-centers-nearby/*",
          "/NATA_Coaching_center_near_me_address",
          "/Application-form-Nata-Coaching",
          "/Free-Nata-Class-books-online-registration",
          "/NATA_Application_Form_*",
          "/FAQs-nata-exam-questions",
          "/JEE_B.arch_Syllabus",
          "/NATA_Best_Architecture_Colleges",
          "/NATA_Free_Books",
          "/materials",
          // Disallow all .html files (duplicates)
          "/*.html",
          // Special characters
          "/&",
          "/$",
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
  };
}
